# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e546d09ea38db285303cd775282eda2e796f4fc9d7c384e897f4fb3be038a8e3c6fe72e693d2e67de8d2f99b55b5779b8c1d795fae76a11b17c816274a09192

test:
  secret_key_base: 37a3b80b824b71804eb5343beb9c98f73a54f45ce7306fc47f95f02408f7e6a4f852ca25894b81e55e9b619ab56ad25c1adb42704159f075941587cda9a4d316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
